/**
 * Generates docs/SOUP.md from target/sbom.json.
 *
 * IEC 62304 wants every third-party item that ships in the device identified by title,
 * manufacturer and unique version designator (8.1.2), with the purpose it serves (5.3.3) and a
 * route to its published anomaly list (7.1.2). The CycloneDX SBOM the Maven build already
 * produces carries all of that except the purpose, which is a statement about this device rather
 * than about the library — so purposes for the direct dependencies live in PURPOSE below, and
 * every transitive item is attributed to the direct dependency that pulls it in.
 *
 * Generated rather than written, because a hand-kept SOUP list goes stale silently the first
 * time a transitive version moves. Run `node tools/soup-list.mjs` after
 * `mvn package`; the check below fails if a direct dependency has no purpose recorded, so
 * adding one to the POM cannot skip this file.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const PURPOSE = {
	'org.springframework.boot:spring-boot-starter':
		'Dependency injection, configuration binding and logging.',
	'org.springframework.boot:spring-boot-starter-tomcat':
		'Embedded servlet container; HAPI\'s RestfulServer is a servlet and requires one.',
	'org.springframework:spring-web':
		'RestClient, for the single outbound XML-RPC call to Prescriptor.',
	'com.zaxxer:HikariCP':
		'JDBC connection pool for the read-only G-Standaard medication code lookup.',
	'ca.uhn.hapi.fhir:hapi-fhir-structures-r4':
		'FHIR R4 resource model, parsers and serialisers for every request and response.',
	'ca.uhn.hapi.fhir:hapi-fhir-server':
		'Annotation-driven FHIR server: operation dispatch, content negotiation, OperationOutcome rendering.',
	'ca.uhn.hapi.fhir:hapi-fhir-validation':
		'Runtime validation of inbound payloads against the published profiles; the source of every 400.',
	'ca.uhn.hapi.fhir:hapi-fhir-validation-resources-r4':
		'The FHIR R4 core conformance resources the validator resolves profiles against.',
	'ca.uhn.hapi.fhir:hapi-fhir-caching-caffeine':
		'Cache provider the validation support chain resolves through a ServiceLoader.',
	'org.mariadb.jdbc:mariadb-java-client':
		'JDBC driver for the G-Standaard reference database.',
};

const bom = JSON.parse(readFileSync('target/sbom.json', 'utf8'));
const root = bom.metadata.component['bom-ref'];
const byRef = new Map(bom.components.map((c) => [c['bom-ref'], c]));
const edges = new Map(bom.dependencies.map((d) => [d.ref, d.dependsOn ?? []]));

const key = (c) => `${c.group}:${c.name}`;
const direct = new Set(edges.get(root) ?? []);

// Shortest path from a direct dependency, so each transitive says who asked for it.
const owner = new Map();
const queue = [...direct].map((ref) => [ref, ref]);
while (queue.length) {
	const [ref, via] = queue.shift();
	if (owner.has(ref)) continue;
	owner.set(ref, via);
	for (const next of edges.get(ref) ?? []) if (!owner.has(next)) queue.push([next, via]);
}

const missing = [...direct].filter((ref) => !PURPOSE[key(byRef.get(ref))]);
if (missing.length) {
	console.error('No purpose recorded for: ' + missing.map((r) => key(byRef.get(r))).join(', '));
	console.error('Add it to PURPOSE in tools/soup-list.mjs — a SOUP item without a stated');
	console.error('purpose does not satisfy IEC 62304 5.3.3.');
	process.exit(1);
}

const licence = (c) =>
	(c.licenses ?? [])
		.map((l) => l.license?.id ?? l.license?.name ?? l.expression)
		.filter(Boolean)
		.join(', ') || '—';

const rows = bom.components
	.map((c) => ({
		name: key(c),
		version: c.version,
		supplier: c.publisher ?? '—',
		licence: licence(c),
		purl: c.purl,
		direct: direct.has(c['bom-ref']),
		via: key(byRef.get(owner.get(c['bom-ref'])) ?? c),
	}))
	.sort((a, b) => Number(b.direct) - Number(a.direct) || a.name.localeCompare(b.name));

const table = (items, withPurpose) =>
	[
		`| Item | Version | Supplier | Licence | ${withPurpose ? 'Purpose in this device' : 'Required by'} |`,
		'|---|---|---|---|---|',
		...items.map(
			(r) =>
				`| \`${r.name}\` | ${r.version} | ${r.supplier} | ${r.licence} | ` +
				`${withPurpose ? PURPOSE[r.name] : '`' + r.via + '`'} |`,
		),
	].join('\n');

const directRows = rows.filter((r) => r.direct);
const transitiveRows = rows.filter((r) => !r.direct);

const doc = `# SOUP list — ${bom.metadata.component.name} ${bom.metadata.component.version}

<!-- Generated by tools/soup-list.mjs from target/sbom.json. Do not edit by hand. -->

Software of unknown provenance shipped in this device, per IEC 62304 8.1.2. Every item below is
in the deployed artifact. Test-scope dependencies (JUnit, WireMock, H2) are development tools, not
SOUP, and are deliberately absent — the CycloneDX plugin is configured with
\`includeTestScope=false\` so that boundary is enforced by the build rather than asserted here.

The machine-readable equivalent is \`target/sbom.json\` (CycloneDX ${bom.specVersion}), which carries
SHA-512 hashes and package URLs for each item and is the file to feed to vulnerability monitoring.

**${rows.length} items from ${new Set(rows.map((r) => r.supplier)).size} suppliers**: ${directRows.length} integrated directly, ${transitiveRows.length} transitive.

## Directly integrated

${table(directRows, true)}

## Transitive

Each is required by the direct dependency named. They are not selected independently: their
versions are arbitrated by the \`spring-boot-dependencies\` BOM and HAPI's own POMs, and
\`maven-enforcer\`'s \`requireUpperBoundDeps\` fails the build if resolution silently downgrades one.

${table(transitiveRows, false)}
`;

mkdirSync('docs', { recursive: true });
writeFileSync('docs/SOUP.md', doc);
console.log(`docs/SOUP.md: ${rows.length} items, ${directRows.length} direct`);
